CREATE TABLE "users" (
	"id" UUID NOT NULL UNIQUE DEFAULT uuidv7(),
	"email" TEXT NOT NULL UNIQUE,
	"name" TEXT NOT NULL,
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"deleted_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);

CREATE TABLE "groups" (
	"id" UUID NOT NULL UNIQUE DEFAULT uuidv7(),
	"managed_by" UUID NOT NULL,
	"name" TEXT NOT NULL,
	"description" TEXT,
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"parent_id" UUID,
	"_lft" BIGINT NOT NULL,
	"_rgt" BIGINT NOT NULL,
	PRIMARY KEY("id")
);

ALTER TABLE "groups"
ADD FOREIGN KEY("managed_by") REFERENCES "users"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "groups"
ADD FOREIGN KEY("parent_id") REFERENCES "groups"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;